the_item_eng=["abyssal-blade","aegis-of-the-immortal","aeon-disk","aether-lens","aghanims-blessing","aghanims-scepter","animal-courier","arcane-boots","armlet-of-mordiggian","assault-cuirass","band-of-elvenskin","battle-fury","belt-of-strength","black-king-bar","blade-mail","blade-of-alacrity","blades-of-attack","blight-stone","blink-dagger","bloodstone","bloodthorn","boots-of-speed","boots-of-travel-level-2","boots-of-travel","bottle","bracer","broadsword","buckler","butterfly","chainmail","cheese","circlet","clarity","claymore","cloak","crimson-guard","crown","crystalys","daedalus","dagon-level-2","dagon-level-3","dagon-level-4","dagon-level-5","dagon","demon-edge","desolator","diffusal-blade","divine-rapier","dragon-lance","drum-of-endurance","dust-of-appearance","eaglesong","echo-sabre","enchanted-mango","energy-booster","ethereal-blade","euls-scepter-of-divinity","eye-of-skadi","faerie-fire","force-staff","gauntlets-of-strength","gem-of-true-sight","ghost-scepter","glimmer-cape","gloves-of-haste","guardian-greaves","hand-of-midas","headdress","healing-salve","heart-of-tarrasque","heavens-halberd","helm-of-iron-will","helm-of-the-dominator","holy-locket","hood-of-defiance","hurricane-pike","hyperstone","infused-raindrops","iron-branch","javelin","kaya-and-sange","kaya","linkens-sphere","lotus-orb","maelstrom","magic-stick","magic-wand","manta-style","mantle-of-intelligence","mask-of-madness","medallion-of-courage","mekansm","meteor-hammer","mithril-hammer","mjollnir","monkey-king-bar","moon-shard","morbid-mask","mystic-staff","necronomicon-level-2","necronomicon-level-3","necronomicon","null-talisman","nullifier","oblivion-staff","observer-and-sentry-wards","observer-ward","octarine-core","ogre-axe","orb-of-venom","orchid-malevolence","perseverance","phase-boots","pipe-of-insight","platemail","point-booster","power-treads","quarterstaff","quelling-blade","radiance","reaver","recipe-aeon-disk","recipe-aether-lens","recipe-aghanims-blessing-2","recipe-armlet-of-mordiggian","recipe-assault-cuirass","recipe-battle-fury","recipe-black-king-bar","recipe-bloodthorn","recipe-boots-of-travel","recipe-bracer","recipe-buckler","recipe-crimson-guard","recipe-crystalys","recipe-daedalus","recipe-dagon","recipe-diffusal-blade","recipe-euls-scepter-of-divinity","recipe-force-staff","recipe-guardian-greaves","recipe-hand-of-midas","recipe-headdress","recipe-heart-of-tarrasque","recipe-helm-of-the-dominator","recipe-holy-locket","recipe-kaya","recipe-linkens-sphere","recipe-magic-wand","recipe-manta-style","recipe-mekansm","recipe-mjollnir","recipe-necronomicon","recipe-null-talisman","recipe-orchid-malevolence","recipe-pipe-of-insight","recipe-radiance","recipe-refresher-orb","recipe-rod-of-atos","recipe-sange","recipe-shivas-guard","recipe-silver-edge","recipe-solar-crest","recipe-soul-ring","recipe-spirit-vessel","recipe-urn-of-shadows","recipe-veil-of-discord","recipe-vladmirs-offering","recipe-yasha","refresher-orb","refresher-shard","ring-of-basilius","ring-of-health","ring-of-protection","ring-of-regen","ring-of-tarrasque","river-vial-blood","river-vial-dry","river-vial-potion","river-vial-slime","robe-of-the-magi","rod-of-atos","sacred-relic","sages-mask","sange-and-yasha","sange","satanic","scythe-of-vyse","sentry-ward","shadow-amulet","shadow-blade","shivas-guard","silver-edge","skull-basher","slippers-of-agility","smoke-of-deceit","solar-crest","soul-booster","soul-ring","spirit-vessel","staff-of-wizardry","stout-shield","super-blink-dagger","talisman-of-evasion","tango-shared","tango","tome-of-knowledge","tranquil-boots","ultimate-orb","urn-of-shadows","vanguard","veil-of-discord","vitality-booster","vladmirs-offering","void-stone","wind-lace","wraith-band","yasha-and-kaya","yasha"]
the_item_ch=["深渊之刃","不朽盾","永恒之盘","以太","蓝色神杖","神杖卷轴","动物信使","秘法鞋","莫迪的臂章","强袭胸甲","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","虚无宝石","风灵纹","","慧夜对剑","夜叉"]

the_item_converted_dic={}

# abyssal-blade:6650
# aegis-of-the-immortal:[]
# aeon-disk:3100
# aether-lens:2350
# aghanims-blessing:6000
# aghanims-scepter:4200
# animal-courier:50
# arcane-boots:1400
# armlet-of-mordiggian:2380
# assault-cuirass:5250
# band-of-elvenskin:450
# battle-fury:4400
# belt-of-strength:450
# black-king-bar:4050
# blade-mail:2200
# blade-of-alacrity:1000
# blades-of-attack:430
# blight-stone:300
# blink-dagger:2250
# bloodstone:4900
# bloodthorn:7205
# boots-of-speed:500
# boots-of-travel-level-2:4500
# boots-of-travel:2500
# bottle:650
# bracer:515
# broadsword:1200
# buckler:800
# butterfly:5475
# chainmail:550
# cheese:1000
# circlet:165
# clarity:50
# claymore:1400
# cloak:550
# crimson-guard:3700
# crown:450
# crystalys:2130
# daedalus:5330
# dagon-level-2:3950
# dagon-level-3:5200
# dagon-level-4:6450
# dagon-level-5:7700
# dagon:2700
# demon-edge:2200
# desolator:3500
# diffusal-blade:3150
# divine-rapier:6000
# dragon-lance:1900
# drum-of-endurance:1625
# dust-of-appearance:180
# eaglesong:3200
# echo-sabre:2650
# enchanted-mango:70
# energy-booster:900
# ethereal-blade:4700
# euls-scepter-of-divinity:2750
# eye-of-skadi:5500
# faerie-fire:70
# force-staff:2250
# gauntlets-of-strength:135
# gem-of-true-sight:900
# ghost-scepter:1500
# glimmer-cape:1950
# gloves-of-haste:500
# guardian-greaves:5475
# hand-of-midas:2150
# headdress:525
# healing-salve:110
# heart-of-tarrasque:5200
# heavens-halberd:3450
# helm-of-iron-will:900
# helm-of-the-dominator:2175
# holy-locket:2700
# hood-of-defiance:1700
# hurricane-pike:4600
# hyperstone:2000
# infused-raindrops:225
# iron-branch:50
# javelin:1100
# kaya-and-sange:4100
# kaya:2050
# linkens-sphere:5050
# lotus-orb:4000
# maelstrom:2700
# magic-stick:200
# magic-wand:450
# manta-style:4700
# mantle-of-intelligence:135
# mask-of-madness:1775
# medallion-of-courage:1175
# mekansm:2275
# meteor-hammer:2625
# mithril-hammer:1600
# mjollnir:5600
# monkey-king-bar:4175
# moon-shard:4000
# morbid-mask:900
# mystic-staff:2700
# necronomicon-level-2:3700
# necronomicon-level-3:5000
# necronomicon:2400
# null-talisman:515
# nullifier:4700
# oblivion-staff:1650
# observer-and-sentry-wards:125
# observer-ward:50
# octarine-core:5900
# ogre-axe:1000
# orb-of-venom:275
# orchid-malevolence:4075
# perseverance:1700
# phase-boots:1480
# pipe-of-insight:3025
# platemail:1400
# point-booster:1200
# power-treads:1450
# quarterstaff:875
# quelling-blade:200
# radiance:5150
# reaver:3000
# recipe-aeon-disk:1100
# recipe-aether-lens:600
# recipe-aghanims-blessing-2:1800
# recipe-armlet-of-mordiggian:550
# recipe-assault-cuirass:1300
# recipe-battle-fury:300
# recipe-black-king-bar:1450
# recipe-bloodthorn:1000
# recipe-boots-of-travel:2000
# recipe-bracer:215
# recipe-buckler:200
# recipe-crimson-guard:750
# recipe-crystalys:500
# recipe-daedalus:1000
# recipe-dagon:1250
# recipe-diffusal-blade:700
# recipe-euls-scepter-of-divinity:650
# recipe-force-staff:950
# recipe-guardian-greaves:1800
# recipe-hand-of-midas:1650
# recipe-headdress:175
# recipe-heart-of-tarrasque:400
# recipe-helm-of-the-dominator:300
# recipe-holy-locket:550
# recipe-kaya:600
# recipe-linkens-sphere:1200
# recipe-magic-wand:150
# recipe-manta-style:500
# recipe-mekansm:950
# recipe-mjollnir:900
# recipe-necronomicon:1300
# recipe-null-talisman:215
# recipe-orchid-malevolence:775
# recipe-pipe-of-insight:800
# recipe-radiance:1350
# recipe-refresher-orb:1700
# recipe-rod-of-atos:850
# recipe-sange:600
# recipe-shivas-guard:650
# recipe-silver-edge:600
# recipe-solar-crest:300
# recipe-soul-ring:200
# recipe-spirit-vessel:750
# recipe-urn-of-shadows:310
# recipe-veil-of-discord:700
# recipe-vladmirs-offering:525
# recipe-yasha:600
# refresher-orb:5100
# refresher-shard:1000
# ring-of-basilius:500
# ring-of-health:850
# ring-of-protection:175
# ring-of-regen:300
# ring-of-tarrasque:700
# river-vial-blood:[]
# river-vial-dry:[]
# river-vial-potion:[]
# river-vial-slime:[]
# robe-of-the-magi:450
# rod-of-atos:2750
# sacred-relic:3800
# sages-mask:325
# sange-and-yasha:4100
# sange:2050
# satanic:5300
# scythe-of-vyse:5700
# sentry-ward:75
# shadow-amulet:1400
# shadow-blade:2800
# shivas-guard:4750
# silver-edge:5550
# skull-basher:2950
# slippers-of-agility:135
# smoke-of-deceit:80
# solar-crest:3875
# soul-booster:3200
# soul-ring:770
# spirit-vessel:2975
# staff-of-wizardry:1000
# stout-shield:200
# super-blink-dagger:[]
# talisman-of-evasion:1400
# tango-shared:30
# tango:90
# tome-of-knowledge:150
# tranquil-boots:1050
# ultimate-orb:2150
# urn-of-shadows:875
# vanguard:2150
# veil-of-discord:2050
# vitality-booster:1100
# vladmirs-offering:1925
# void-stone:850
# wind-lace:250
# wraith-band:515
# yasha-and-kaya:4100
# yasha:2050
